language: cpp

sudo: required

services:
- docker

env:
  matrix:
  - APP=amg
  - APP=candle-benchmarks DEPS="python" # no tensorflow in spack
  - APP=examinimd
  - APP=laghos
  - APP=macsio
  - APP=miniamr
  - APP=minife
  - APP=minitri
  - APP=nekbone
  - APP=sw4lite
  - APP=swfft
  - APP=xsbench
  - APP=amg2013
  - APP=aspa
  - APP=branson
  - APP=clamr
  - APP=cloverleaf
  - APP=cloverleaf3d
  - APP=coevp
  - APP=cohmm
  - APP=comd
  - APP=cosp2
  - APP=ebms
  - APP=exampm
  - APP=exasp2
  - APP=hacckernels
  - APP=hpccg
  - APP=hpgmg
  - APP=kripke
  - APP=lcals
  - APP=lulesh
  - APP=miniaero
  - APP=miniamr
  - APP=minighost
  - APP=minimd
  - APP=miniqmc
  - APP=minismac2d
  - APP=minixyce
  - APP=nut
  - APP=openmc
  - APP=pathfinder
  - APP=pennant
  - APP=rsbench
  - APP=simplemoc
  - APP=snap
  - APP=snbone
  - APP=tealeaf

before_install:
  - cp -vr docker ${HOME}/docker
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - cp -r $HOME/.ccache ${HOME}/docker/ccache
  - git clone --depth 1 https://github.com/spack/spack ${HOME}/docker/spack
  - source ${HOME}/docker/spack/share/spack/setup-env.sh
  - if spack info ${APP} | grep -q mantevo.org/downloads; then INSECURE="--insecure"; fi
  - for i in $(spack list -t proxy-app | grep -v ecp-proxy-apps); do echo "Looking for $i"; grep -q "APP=$i" ${HOME}/docker/proxy-ci/.travis.yml || exit 1; done

script:
  - docker build 
                --build-arg APP="${APP}"
                --build-arg DEPS="${DEPS}"
                --build-arg INSECURE="${INSECURE}"
                -t ${TRAVIS_REPO_SLUG}:latest ${HOME}/docker/ &&
    rm -rf ${HOME}/.ccache &&
    CON=$(docker run -d ${TRAVIS_REPO_SLUG}:latest /bin/bash) &&
    docker cp ${CON}:/home/ci/.ccache ${HOME}/

cache:
  ccache: true

compiler:
- gcc
