language: cpp
addons:
  apt:
    packages:
    - gfortran
    - mercurial
    - graphviz
    - gnupg2
    - r-base
    - r-base-core
    - r-base-dev
    - perl
    - perl-base
    - libopenmpi-dev
env:
  matrix:
  - APP=amg
  - APP=candle-benchmarks DEPS=no # no tensorflow in spack
  - APP=examinimd
  - APP=laghos
  - APP=macsio
  - APP=miniamr
  - APP=minife
  - APP=minitri
  - APP=nekbone
  - APP=sw4lite
  - APP=swfft
  - APP=xsbench
  - APP=amg2013
  - APP=aspa
  - APP=branson
  - APP=clamr
  - APP=cloverleaf
  - APP=cloverleaf3d
  - APP=coevp
  - APP=cohmm
  - APP=comd
  - APP=cosp2
  - APP=ebms
  - APP=exampm
  - APP=exasp2
  - APP=hacckernels
  - APP=hpccg
  - APP=hpgmg
  - APP=kripke
  - APP=lcals
  - APP=lulesh
  - APP=miniaero
  - APP=miniamr
  - APP=minighost
  - APP=minimd
  - APP=miniqmc
  - APP=minismac2d
  - APP=minixyce
  - APP=nut
  - APP=openmc
  - APP=pathfinder
  - APP=pennant
  - APP=rsbench
  - APP=simplemoc
  - APP=snap
  - APP=snbone
  - APP=tealeaf
matrix:
  allow_failures:
  - env: APP=amg2013
  - env: APP=aspa
  - env: APP=branson
  - env: APP=clamr
  - env: APP=cloverleaf
  - env: APP=cloverleaf3d
  - env: APP=coevp
  - env: APP=cohmm
  - env: APP=cosp2
  - env: APP=ebms
  - env: APP=exampm
  - env: APP=exasp2
  - env: APP=hacckernels
  - env: APP=hpccg
  - env: APP=hpgmg
  - env: APP=kripke
  - env: APP=lcals
  - env: APP=lulesh
  - env: APP=miniaero
  - env: APP=miniamr
  - env: APP=minighost
  - env: APP=minimd
  - env: APP=miniqmc
  - env: APP=minismac2d
  - env: APP=minixyce
  - env: APP=nut
  - env: APP=openmc
  - env: APP=pathfinder
  - env: APP=pennant
  - env: APP=rsbench
  - env: APP=simplemoc
  - env: APP=snap
  - env: APP=snbone
  - env: APP=tealeaf
before_install:
- git clone --depth 1 https://github.com/spack/spack
- source spack/share/spack/setup-env.sh
- cp packages.yaml spack/etc/spack/packages.yaml
script:
- if [[ ${DEPS} != "no" ]]; then travis_wait 40 spack install -j4 --only dependencies ${APP}; fi
- if spack info ${APP} | grep -q mantevo.org/downloads; then INSECURE="--insecure"; fi
- spack ${INSECURE} install -j4 --only package -v ${APP}
cache:
  ccache: true
compiler:
- gcc
notifications:
  email:
    recipients:
      secure: AxSotx9wJR5HqsqWFNbY6Kd2TuzSXcWzClBtP0Va7eCwf9XlspzVNp4t+o4GQhcurVeR5cT0BMHak+DtgWrsgkwEQNVHXpOsaEDf1yZgmAv+9K9EWvtPyjXNcJEax0AMdHDAZJkF9ZqyCwzfMJaeC7XZyWBdODBwQIWa9RnSLD0B7BnehzP7UERfk4oUGhDcuvJJa9qm51o2czTQK7Wpbi7OXdRkFfYTQZD0F8YRUmMeGTpcX+hQDKuFm0qVYMLBKu5ZwzO1iGTZgIzFPEHznbq9TX5eyS8IIgefuVwI/iiOkEXc9jfa1gT7piAGveHBpeMjA3HxgwkSuwYMge+3P5NK8YywakPBoeBkdNnXNgj/8Dkx5aLwlTmhYEUxNjwE7oBpOqFnxfRHdmuZgonxuIZniPwL+LYdOdCE+38CqHFo0nR5D0eAjdVmnqt73JIlckuXWuWOf3SEfvkaoJm1KX4xFAWKmcWN3AxuoDeRV+hD/UK0XO9nI5SNtwd57P29Ee1ZaDW4mZ9c5GJ0vDmvhliWwjW5cEDAB4e8ZPEKwNhdEuwnRuSwA82eXSVjlHfCLYEmedK3B7qOP0sMEQBYpooHllD2fd0jwEqhr80wdIUW6V7izUEaaq8E3xMTXgHHs+OvSbia+aR+PCddRJRXy2j+zP7Fnbw41VZ0Q0qNgXQ=
