language: cpp

addons:
  apt:
    packages:
      - gfortran
      
env:
  matrix:
    - APP=amg
# no tensorflow    - APP=candle-benchmarks
    - APP=comd
    - APP=laghos
    - APP=macsio
    - APP=miniamr
    - APP=minife
    - APP=minitri
    - APP=nekbone
    - APP=sw4lite
    - APP=swfft
    - APP=xsbench

before_install:
 - git clone --depth 1 https://github.com/spack/spack
 - source spack/share/spack/setup-env.sh

script:
  - spack install -j2 --only dependencies ${APP}
  - spack install -j2 -v ${APP}

cache:
  ccache: true

compiler:
  - gcc
